M48
; DRILL file {KiCad 9.0.4} date 2025-09-02T02:13:20+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-02T02:13:20+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X194.75Y-103.05
T2
X215.75Y-103.05
T3
X135.75Y-76.5
X135.75Y-121.75
X176.0Y-86.0
M30
